webdriver {
  driver = "chrome"
}

serenity {
  project.name = "Framework Automatización"
  reports = ["single-page-html"]
  outputDirectory = "target/site/serenity"
  take.screenshots = FOR_EACH_ACTION
  logging = QUIET
  compress.filenames = true
  report.language = es
}

chrome.switches = "--start-maximized,--disable-notifications,--incognito"

reports {
  show.step.details = true
}

cucumber {
  filter.tags = ""
}

headless.mode = false